// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: media_exporter.proto

package media_exporter

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to generate export
type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Agent ID
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	From          int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_media_exporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_exporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_media_exporter_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ExportRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ExportRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ExportRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

// Request to download export
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`             // Task identifier from GeneratePDF
	DomainID      int64                  `protobuf:"varint,2,opt,name=domainID,proto3" json:"domainID,omitempty"` // Domain ID for authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_media_exporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_exporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_media_exporter_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DownloadRequest) GetDomainID() int64 {
	if x != nil {
		return x.DomainID
	}
	return 0
}

// Metadata about export
type ExportMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // e.g., "application/pdf"
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                     // pending | processing | done | failed
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`                        // optional, 0 if not ready
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportMetadata) Reset() {
	*x = ExportMetadata{}
	mi := &file_media_exporter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetadata) ProtoMessage() {}

func (x *ExportMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_media_exporter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetadata.ProtoReflect.Descriptor instead.
func (*ExportMetadata) Descriptor() ([]byte, []int) {
	return file_media_exporter_proto_rawDescGZIP(), []int{2}
}

func (x *ExportMetadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExportMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExportMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ExportMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExportMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Response with PDF chunk
type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_media_exporter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_exporter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_media_exporter_proto_rawDescGZIP(), []int{3}
}

func (x *ExportResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_media_exporter_proto protoreflect.FileDescriptor

const file_media_exporter_proto_rawDesc = "" +
	"\n" +
	"\x14media_exporter.proto\x12\x15webitel.mediaexporter\x1a\x1cgoogle/api/annotations.proto\"h\n" +
	"\rExportRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\"=\n" +
	"\x0fDownloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bdomainID\x18\x02 \x01(\x03R\bdomainID\"\x8f\x01\n" +
	"\x0eExportMetadata\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"&\n" +
	"\x0eExportResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\x9c\x02\n" +
	"\x14MediaExporterService\x12\x83\x01\n" +
	"\vGeneratePDF\x12$.webitel.mediaexporter.ExportRequest\x1a%.webitel.mediaexporter.ExportMetadata\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/export/media/{agent_id}/pdf\x12~\n" +
	"\vDownloadPDF\x12&.webitel.mediaexporter.DownloadRequest\x1a%.webitel.mediaexporter.ExportResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/export/media/{id}/pdf0\x01B\xe9\x01\n" +
	"\x19com.webitel.mediaexporterB\x12MediaExporterProtoP\x01ZCgithub.com/webitel/media-exporter/api/media_exporter;media_exporter\xa2\x02\x03WMX\xaa\x02\x15Webitel.Mediaexporter\xca\x02\x15Webitel\\Mediaexporter\xe2\x02!Webitel\\Mediaexporter\\GPBMetadata\xea\x02\x16Webitel::Mediaexporterb\x06proto3"

var (
	file_media_exporter_proto_rawDescOnce sync.Once
	file_media_exporter_proto_rawDescData []byte
)

func file_media_exporter_proto_rawDescGZIP() []byte {
	file_media_exporter_proto_rawDescOnce.Do(func() {
		file_media_exporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_exporter_proto_rawDesc), len(file_media_exporter_proto_rawDesc)))
	})
	return file_media_exporter_proto_rawDescData
}

var file_media_exporter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_media_exporter_proto_goTypes = []any{
	(*ExportRequest)(nil),   // 0: webitel.mediaexporter.ExportRequest
	(*DownloadRequest)(nil), // 1: webitel.mediaexporter.DownloadRequest
	(*ExportMetadata)(nil),  // 2: webitel.mediaexporter.ExportMetadata
	(*ExportResponse)(nil),  // 3: webitel.mediaexporter.ExportResponse
}
var file_media_exporter_proto_depIdxs = []int32{
	0, // 0: webitel.mediaexporter.MediaExporterService.GeneratePDF:input_type -> webitel.mediaexporter.ExportRequest
	1, // 1: webitel.mediaexporter.MediaExporterService.DownloadPDF:input_type -> webitel.mediaexporter.DownloadRequest
	2, // 2: webitel.mediaexporter.MediaExporterService.GeneratePDF:output_type -> webitel.mediaexporter.ExportMetadata
	3, // 3: webitel.mediaexporter.MediaExporterService.DownloadPDF:output_type -> webitel.mediaexporter.ExportResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_exporter_proto_init() }
func file_media_exporter_proto_init() {
	if File_media_exporter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_exporter_proto_rawDesc), len(file_media_exporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_exporter_proto_goTypes,
		DependencyIndexes: file_media_exporter_proto_depIdxs,
		MessageInfos:      file_media_exporter_proto_msgTypes,
	}.Build()
	File_media_exporter_proto = out.File
	file_media_exporter_proto_goTypes = nil
	file_media_exporter_proto_depIdxs = nil
}
