// Code generated by protoc-gen-go-webitel. DO NOT EDIT.
// versions:
// - protoc-gen-go-webitel v1.0.0
// - protoc                (unknown)

package media_exporter

// WebitelServicesInfo is the list of services defined in proto files.
type WebitelServicesInfo map[string]WebitelServices

type WebitelServices struct {
	ObjClass           string
	AdditionalLicenses []string
	WebitelMethods     map[string]WebitelMethod
}

// WebitelMethod is the list of methods defined in this service.
type WebitelMethod struct {
	HttpBindings []*HttpBinding
	Access       int
	Input        string
	Output       string
}

type HttpBinding struct {
	Path   string
	Method string
}

var WebitelAPI = WebitelServicesInfo{
	"MediaExporterService": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"GeneratePDF": WebitelMethod{
				Access: 0,
				Input:  "ExportRequest",
				Output: "ExportMetadata",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/media/{agent_id}/pdf",
						Method: "POST",
					},
				},
			},
			"DownloadPDF": WebitelMethod{
				Access: 0,
				Input:  "DownloadRequest",
				Output: "ExportResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/media/{task_id}/pdf",
						Method: "GET",
					},
				},
			},
		},
	},
}
