// Code generated by protoc-gen-go-webitel. DO NOT EDIT.
// versions:
// - protoc-gen-go-webitel v1.0.0
// - protoc                (unknown)

package pdf

// WebitelServicesInfo is the list of services defined in proto files.
type WebitelServicesInfo map[string]WebitelServices

type WebitelServices struct {
	ObjClass           string
	AdditionalLicenses []string
	WebitelMethods     map[string]WebitelMethod
}

// WebitelMethod is the list of methods defined in this service.
type WebitelMethod struct {
	HttpBindings []*HttpBinding
	Access       int
	Input        string
	Output       string
}

type HttpBinding struct {
	Path   string
	Method string
}

var WebitelAPI = WebitelServicesInfo{
	"PdfService": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"CreateScreenrecordingExport": WebitelMethod{
				Access: 0,
				Input:  "CreateScreenrecordingRequest",
				Output: "ExportTask",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/agents/{agent_id}/exports/pdf/screenrecordings",
						Method: "POST",
					},
				},
			},
			"ListScreenrecordingExports": WebitelMethod{
				Access: 0,
				Input:  "ListScreenrecordingHistoryRequest",
				Output: "ListExportsResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/agents/{agent_id}/exports/pdf/screenrecordings",
						Method: "GET",
					},
				},
			},
			"CreateCallExport": WebitelMethod{
				Access: 0,
				Input:  "CreateCallExportRequest",
				Output: "ExportTask",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/calls/{call_id}/exports/pdf",
						Method: "POST",
					},
				},
			},
			"ListCallExports": WebitelMethod{
				Access: 0,
				Input:  "ListCallHistoryRequest",
				Output: "ListExportsResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/calls/{call_id}/exports/pdf",
						Method: "GET",
					},
				},
			},
			"DeleteExport": WebitelMethod{
				Access: 0,
				Input:  "DeleteExportRequest",
				Output: "DeleteExportResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/exports/pdf/history/{id}",
						Method: "DELETE",
					},
				},
			},
		},
	},
}
