// Code generated by protoc-gen-go-webitel. DO NOT EDIT.
// versions:
// - protoc-gen-go-webitel v1.0.0
// - protoc                (unknown)

package pdf

// WebitelServicesInfo is the list of services defined in proto files.
type WebitelServicesInfo map[string]WebitelServices

type WebitelServices struct {
	ObjClass           string
	AdditionalLicenses []string
	WebitelMethods     map[string]WebitelMethod
}

// WebitelMethod is the list of methods defined in this service.
type WebitelMethod struct {
	HttpBindings []*HttpBinding
	Access       int
	Input        string
	Output       string
}

type HttpBinding struct {
	Path   string
	Method string
}

var WebitelAPI = WebitelServicesInfo{
	"PdfService": WebitelServices{
		ObjClass:           "",
		AdditionalLicenses: []string{},
		WebitelMethods: map[string]WebitelMethod{
			"GenerateScreenrecordingPdfExport": WebitelMethod{
				Access: 0,
				Input:  "ScreenrecordingPdfGenerateRequest",
				Output: "PdfExportMetadata",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/pdf/{agent_id}",
						Method: "POST",
					},
				},
			},
			"DownloadPdfExport": WebitelMethod{
				Access: 0,
				Input:  "PdfDownloadRequest",
				Output: "PdfExportChunk",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/pdf/{file_id}",
						Method: "GET",
					},
				},
			},
			"GetScreenrecordingPdfExportHistory": WebitelMethod{
				Access: 0,
				Input:  "PdfScreenrecordingHistoryRequest",
				Output: "PdfHistoryResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/pdf/{agent_id}/history",
						Method: "GET",
					},
				},
			},
			"GenerateCallPdfExport": WebitelMethod{
				Access: 0,
				Input:  "PdfGenerateCallPdfRequest",
				Output: "PdfExportMetadata",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/pdf/call/{call_id}",
						Method: "POST",
					},
				},
			},
			"GetCallPdfHistory": WebitelMethod{
				Access: 0,
				Input:  "PdfCallPdfHistoryRequest",
				Output: "PdfHistoryResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/pdf/call/{call_id}/history",
						Method: "GET",
					},
				},
			},
			"DeletePdfExportRecord": WebitelMethod{
				Access: 0,
				Input:  "DeletePdfExportRecordRequest",
				Output: "DeletePdfExportRecordResponse",
				HttpBindings: []*HttpBinding{
					{
						Path:   "/export/pdf/history/{id}",
						Method: "DELETE",
					},
				},
			},
		},
	},
}
