// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pdf.proto

package pdf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdfService_CreateScreenrecordingExport_FullMethodName = "/webitel_media_exporter.PdfService/CreateScreenrecordingExport"
	PdfService_ListScreenrecordingExports_FullMethodName  = "/webitel_media_exporter.PdfService/ListScreenrecordingExports"
	PdfService_CreateCallExport_FullMethodName            = "/webitel_media_exporter.PdfService/CreateCallExport"
	PdfService_ListCallExports_FullMethodName             = "/webitel_media_exporter.PdfService/ListCallExports"
	PdfService_DownloadCallArchive_FullMethodName         = "/webitel_media_exporter.PdfService/DownloadCallArchive"
	PdfService_DeleteExport_FullMethodName                = "/webitel_media_exporter.PdfService/DeleteExport"
)

// PdfServiceClient is the client API for PdfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PdfService provides methods to asynchronously generate, list,
// and manage PDF exports from different media sources.
type PdfServiceClient interface {
	// Creates a new task to generate a PDF export for an agent's screen recordings.
	// This operation is asynchronous and returns a task metadata.
	CreateScreenrecordingExport(ctx context.Context, in *CreateScreenrecordingRequest, opts ...grpc.CallOption) (*ExportTask, error)
	// Lists the history of PDF exports for a specific agent.
	ListScreenrecordingExports(ctx context.Context, in *ListScreenrecordingHistoryRequest, opts ...grpc.CallOption) (*ListExportsResponse, error)
	// Creates a new task to generate a PDF export for a specific call.
	// Useful for documenting call transcripts or associated media.
	CreateCallExport(ctx context.Context, in *CreateCallExportRequest, opts ...grpc.CallOption) (*ExportTask, error)
	// Lists the history of PDF exports for a specific call ID.
	ListCallExports(ctx context.Context, in *ListCallHistoryRequest, opts ...grpc.CallOption) (*ListExportsResponse, error)
	// Streams a ZIP archive bundling the given, already-uploaded call files (e.g. PDFs).
	// Synchronous: the archive is assembled on the fly and streamed back chunk by chunk,
	// so the caller does not need to poll for completion or a separate download step.
	DownloadCallArchive(ctx context.Context, in *DownloadCallArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadCallArchiveResponse], error)
	// Deletes a specific export record from the history.
	DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*DeleteExportResponse, error)
}

type pdfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfServiceClient(cc grpc.ClientConnInterface) PdfServiceClient {
	return &pdfServiceClient{cc}
}

func (c *pdfServiceClient) CreateScreenrecordingExport(ctx context.Context, in *CreateScreenrecordingRequest, opts ...grpc.CallOption) (*ExportTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportTask)
	err := c.cc.Invoke(ctx, PdfService_CreateScreenrecordingExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdfServiceClient) ListScreenrecordingExports(ctx context.Context, in *ListScreenrecordingHistoryRequest, opts ...grpc.CallOption) (*ListExportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExportsResponse)
	err := c.cc.Invoke(ctx, PdfService_ListScreenrecordingExports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdfServiceClient) CreateCallExport(ctx context.Context, in *CreateCallExportRequest, opts ...grpc.CallOption) (*ExportTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportTask)
	err := c.cc.Invoke(ctx, PdfService_CreateCallExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdfServiceClient) ListCallExports(ctx context.Context, in *ListCallHistoryRequest, opts ...grpc.CallOption) (*ListExportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExportsResponse)
	err := c.cc.Invoke(ctx, PdfService_ListCallExports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pdfServiceClient) DownloadCallArchive(ctx context.Context, in *DownloadCallArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadCallArchiveResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PdfService_ServiceDesc.Streams[0], PdfService_DownloadCallArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadCallArchiveRequest, DownloadCallArchiveResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PdfService_DownloadCallArchiveClient = grpc.ServerStreamingClient[DownloadCallArchiveResponse]

func (c *pdfServiceClient) DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*DeleteExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExportResponse)
	err := c.cc.Invoke(ctx, PdfService_DeleteExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfServiceServer is the server API for PdfService service.
// All implementations must embed UnimplementedPdfServiceServer
// for forward compatibility.
//
// PdfService provides methods to asynchronously generate, list,
// and manage PDF exports from different media sources.
type PdfServiceServer interface {
	// Creates a new task to generate a PDF export for an agent's screen recordings.
	// This operation is asynchronous and returns a task metadata.
	CreateScreenrecordingExport(context.Context, *CreateScreenrecordingRequest) (*ExportTask, error)
	// Lists the history of PDF exports for a specific agent.
	ListScreenrecordingExports(context.Context, *ListScreenrecordingHistoryRequest) (*ListExportsResponse, error)
	// Creates a new task to generate a PDF export for a specific call.
	// Useful for documenting call transcripts or associated media.
	CreateCallExport(context.Context, *CreateCallExportRequest) (*ExportTask, error)
	// Lists the history of PDF exports for a specific call ID.
	ListCallExports(context.Context, *ListCallHistoryRequest) (*ListExportsResponse, error)
	// Streams a ZIP archive bundling the given, already-uploaded call files (e.g. PDFs).
	// Synchronous: the archive is assembled on the fly and streamed back chunk by chunk,
	// so the caller does not need to poll for completion or a separate download step.
	DownloadCallArchive(*DownloadCallArchiveRequest, grpc.ServerStreamingServer[DownloadCallArchiveResponse]) error
	// Deletes a specific export record from the history.
	DeleteExport(context.Context, *DeleteExportRequest) (*DeleteExportResponse, error)
	mustEmbedUnimplementedPdfServiceServer()
}

// UnimplementedPdfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdfServiceServer struct{}

func (UnimplementedPdfServiceServer) CreateScreenrecordingExport(context.Context, *CreateScreenrecordingRequest) (*ExportTask, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScreenrecordingExport not implemented")
}
func (UnimplementedPdfServiceServer) ListScreenrecordingExports(context.Context, *ListScreenrecordingHistoryRequest) (*ListExportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScreenrecordingExports not implemented")
}
func (UnimplementedPdfServiceServer) CreateCallExport(context.Context, *CreateCallExportRequest) (*ExportTask, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCallExport not implemented")
}
func (UnimplementedPdfServiceServer) ListCallExports(context.Context, *ListCallHistoryRequest) (*ListExportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCallExports not implemented")
}
func (UnimplementedPdfServiceServer) DownloadCallArchive(*DownloadCallArchiveRequest, grpc.ServerStreamingServer[DownloadCallArchiveResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadCallArchive not implemented")
}
func (UnimplementedPdfServiceServer) DeleteExport(context.Context, *DeleteExportRequest) (*DeleteExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExport not implemented")
}
func (UnimplementedPdfServiceServer) mustEmbedUnimplementedPdfServiceServer() {}
func (UnimplementedPdfServiceServer) testEmbeddedByValue()                    {}

// UnsafePdfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfServiceServer will
// result in compilation errors.
type UnsafePdfServiceServer interface {
	mustEmbedUnimplementedPdfServiceServer()
}

func RegisterPdfServiceServer(s grpc.ServiceRegistrar, srv PdfServiceServer) {
	// If the following call panics, it indicates UnimplementedPdfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdfService_ServiceDesc, srv)
}

func _PdfService_CreateScreenrecordingExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScreenrecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).CreateScreenrecordingExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfService_CreateScreenrecordingExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).CreateScreenrecordingExport(ctx, req.(*CreateScreenrecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdfService_ListScreenrecordingExports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScreenrecordingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).ListScreenrecordingExports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfService_ListScreenrecordingExports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).ListScreenrecordingExports(ctx, req.(*ListScreenrecordingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdfService_CreateCallExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCallExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).CreateCallExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfService_CreateCallExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).CreateCallExport(ctx, req.(*CreateCallExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdfService_ListCallExports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCallHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).ListCallExports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfService_ListCallExports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).ListCallExports(ctx, req.(*ListCallHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PdfService_DownloadCallArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadCallArchiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PdfServiceServer).DownloadCallArchive(m, &grpc.GenericServerStream[DownloadCallArchiveRequest, DownloadCallArchiveResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PdfService_DownloadCallArchiveServer = grpc.ServerStreamingServer[DownloadCallArchiveResponse]

func _PdfService_DeleteExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfServiceServer).DeleteExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfService_DeleteExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfServiceServer).DeleteExport(ctx, req.(*DeleteExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PdfService_ServiceDesc is the grpc.ServiceDesc for PdfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webitel_media_exporter.PdfService",
	HandlerType: (*PdfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScreenrecordingExport",
			Handler:    _PdfService_CreateScreenrecordingExport_Handler,
		},
		{
			MethodName: "ListScreenrecordingExports",
			Handler:    _PdfService_ListScreenrecordingExports_Handler,
		},
		{
			MethodName: "CreateCallExport",
			Handler:    _PdfService_CreateCallExport_Handler,
		},
		{
			MethodName: "ListCallExports",
			Handler:    _PdfService_ListCallExports_Handler,
		},
		{
			MethodName: "DeleteExport",
			Handler:    _PdfService_DeleteExport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadCallArchive",
			Handler:       _PdfService_DownloadCallArchive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pdf.proto",
}
